version: '3.8'

services:
  database:
    container_name: ttt-database-gp
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tictactoe
      MYSQL_USER: tictactoe
      MYSQL_PASSWORD: password
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql

  php:
    container_name: ttt-php-gp
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/tictactoe
    depends_on:
      - ttt-database-gp

  nginx:
    container_name: ttt-nginx-gp
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/tictactoe
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ttt-php-gp
      - ttt-database-gp